### ISSUE TITLE
如何添加更多包呢？

### ISSUE THREAD

**Issue by ocorz** [Angels-Ray/CloudMobilePhone139_SSH#1]
如何添加更多包呢？

**Comment by Angels-Ray** [comment]
> 如何添加更多包呢？

有点不明白你说什么，说具体点？

**Comment by wyr121** [comment]
MagiskSSH里面的软件包：rsync | scp | sftp | sftp-server | ssh | sshd | ssh-keygen

**Comment by ocorz** [comment]
MagiskSSH里面的软件包：rsync | scp | sftp | sftp-server | ssh | sshd | ssh-keygen

能不能添加更多的包呢？

**Comment by Angels-Ray** [comment]
`rsync | scp | sftp | sftp-server | ssh | sshd | ssh-keygen`在`SSH_for_Magisk_by_ATRAY.zip`里都是有的。如果想用其他的，不推荐都放在同一个模块里面，`SSH_for_Magisk_by_ATRAY.zip`是为了适配移动云手机改动了些内容而已。

**Comment by ocorz** [comment]
是的，我看到 “arch\arm64\bin” 里面有 MagiskSSH包括的软件包，不过我的意思是除了这些以外的软件包应该怎么添加呢？arch的pacman能不能添加？如果能pacman安装的软件包是否能用呢？

**Comment by Angels-Ray** [comment]
`pacman`应该是不能简单适配安卓的文件系统结构的，你可以在github上找找有没有大佬适配了。添加其他软件包：如果不用magisk，可以将编译后的可执行文件直接丢进bin里面；用magisk需要学会自己写模块

**Comment by ocorz** [comment]
感谢回答，你在使用云手机ssh的过程中有什么推荐的包吗？
